// <auto-generated />
using System;
using Assignment5Gearhart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment5Gearhart.Migrations
{
    [DbContext(typeof(FuelContext))]
    partial class FuelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment5Gearhart.Models.FuelRecordModel", b =>
                {
                    b.Property<int>("FuelRecordModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datePurchased")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("mileage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("numberGallons")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("pricePaid")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("FuelRecordModelId");

                    b.ToTable("FuelRecordModels");

                    b.HasData(
                        new
                        {
                            FuelRecordModelId = 1,
                            datePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            mileage = 0m,
                            numberGallons = 0m,
                            pricePaid = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
